function obj = scaleObj(obj,lengthScaleFactor,densityScaleFactor)
% function that uses the listed units to automatically scale up/down
p = properties(obj);
scaleUnitList = {'m','s','kg','rad','deg','N','Pa'}; % units that impact how to scale things

scaleFactors  = {...
    num2str(lengthScaleFactor),...
    num2str(sqrt(lengthScaleFactor)),...
    num2str(lengthScaleFactor^3),...
    '1',...
    '1',...
    num2str(lengthScaleFactor^3),...
    num2str(lengthScaleFactor)};

for ii = 1:length(p)
    unit = obj.(p{ii}).Unit;
    if ~isempty(unit)
        if and(...
                ~contains(obj.(p{ii}).Description,'grav','IgnoreCase',true) ,...
                and(any(strcmp(obj.(p{ii}).Unit,{'m/s^2','m*s^-2'})) ,...
                fix(10*obj.(p{ii}).Value)/10 == 9.8)) ...
                ||...
                and(~contains(obj.(p{ii}).Description,'visc','IgnoreCase',true),...
                and(any(strcmp(obj.(p{ii}).Unit,{'Pa*s','kg/(m*s)'})) ,...
                any(fix(obj.(p{ii}).Value) == [1e-3 1e-5])))
            for jj = 1:length(scaleUnitList)
                unit = strrep(unit, scaleUnitList{jj},scaleFactors{jj});
            end
            scaleFactor = eval(unit);
            obj.(p{ii}).Value = obj.(p{ii}).Value*scaleFactor;
        end
    end
end
end
