del .\compositions\environment\flowCalculation\constT_XYZvarZ_Ramp\library\constT_XYZvarZ_Ramp.mat
del .\compositions\environment\flowCalculation\constXYZT\library\constXYZT.mat
del .\compositions\environment\flowCalculation\constXYZT\library\ayazAirborneFlow\ayazAirborneFlow.mat
del .\compositions\environment\flowCalculation\constXYZ_varT_SineWave\library\constXYZ_varT_SineWave.mat
del .\compositions\environment\flowCalculation\constYZTvarX\library\constYZTvarX.mat
del .\compositions\environment\flowCalculation\lowFreqWithFAUTurb\library\CNAPsNoTurbJosh\CNAPsNoTurbJosh.mat
del .\compositions\environment\flowCalculation\lowFreqWithFAUTurb\library\CNAPsTurbJames\CNAPsTurbJames.mat
del .\compositions\environment\flowCalculation\lowFreqWithFAUTurb\library\CNAPsTurbMitchell\CNAPsTurbMitchell.mat
del .\compositions\environment\flowCalculation\lowFreqWithFAUTurb\library\DARPATurbJames\DARPATurbJames.mat
del .\compositions\environment\flowCalculation\lowFreqWithFauTurbAndWaves\library\CNAPsTurbJames.mat
del .\compositions\environment\flowCalculation\planarWaveModel\library\hurricaneSandyWave.mat
del .\compositions\environment\flowCalculation\steppedLateralFlow\library\steppedLateralFlow.mat
del .\compositions\environment\flowCalculation\syntheticFlow\library\ayazAirborneSynFlow.mat
del .\compositions\environment\flowCalculation\syntheticFlow\library\ayazSynFlow.mat
del .\compositions\flightController\fullCycleController\library\fullCycleCtrl\fullCycleCtrl.mat
del .\compositions\flightController\guidanceLawPathFollowing\library\guidanceLawPathFollowingAir\guidanceLawPathFollowingAir.mat
del .\compositions\flightController\guidanceLawPathFollowing\library\guidanceLawPathFollowingWater\guidanceLawPathFollowingWater.mat
del .\compositions\flightController\pathFollowingController\library\pathFollowingCtrlAddedMass\pathFollowingCtrlAddedMass.mat
del .\compositions\flightController\pathFollowingController\library\pathFollowingCtrlForILC\pathFollowingCtrlForILC.mat
del .\compositions\flightController\pathFollowingController\library\pathFollowingCtrlForILC\library\ayazPathFollowingAirborne\ayazPathFollowingAirborne.mat
del .\compositions\flightController\pathFollowingCtrlAoATurb\library\pathFollowCtrlExp.mat
del .\compositions\flightController\pathFollowingCtrlAoATurb\library\pathFollowWithAoACtrlDOE.mat
del .\compositions\flightController\pathFollowingCtrlAoATurb\library\pathFollowingCtrlForManta\pathFollowingCtrlForILCAoA.mat
del .\compositions\flightController\poolTestControllers\library\newSpoolCtrlExp\newSpoolCtrlExp.mat
del .\compositions\flightController\poolTestControllers\library\periodicCtrlExp\periodicCtrlExp.mat
del .\compositions\flightController\shortLeashController\library\slCtrl\exp_slCtrl.mat
del .\compositions\flightController\shortLeashController\library\slCtrl\slCtrl.mat
del .\compositions\flightController\steadyLevelFlightController\library\baselineSteadyLevelFlight\baselineSteadyLevelFlight.mat
del .\compositions\flightController\takeoffToLanding\library\firstBuildTakeoff\firstBuildTakeoff1.mat
del .\compositions\flightController\takeoffToLanding\library\firstBuildTakeoff\firstBuildTakeoff.mat
del .\compositions\flightController\takeoffToLanding\library\jamesMultiCycleExp\jamesMultiCycleExp.mat
del .\compositions\flightController\takeoffToLanding\library\joshMultiCycleExp\joshMultiCycleExp.mat
del .\compositions\flightController\takeoffToLanding\library\newSpoolCtrl\newSpoolCtrl.mat
del .\compositions\flightController\threeTetherThreeSurfaceCtrl\library\ayazThreeTetCtrl\ayazThreeTetCtrl.mat
del .\compositions\gndStnController\anchorTetherCtrl\library\srgSwyHvCtrl\srgSwyHvCtrl.mat
del .\compositions\gndStnController\gliderCtrl\library\motionlessGliderCtrl\motionlessGliderCtrl.mat
del .\compositions\gndStnController\oneDoF\library\oneDoFGSCtrlBasic\oneDoFGSCtrlBasic.mat
del .\compositions\hiLvlController\constantBasisParameters\library\constBoothLem\constBoothLem.mat
del .\compositions\hiLvlController\constantBasisParameters\library\constEllipse\constEllipse.mat
del .\compositions\hiLvlController\gpkfPathOpt\library\gpkfAltitudeOptimization.mat
del .\compositions\hiLvlController\gpkfPathOpt\library\gpkfPathOptAirborne.mat
del .\compositions\hiLvlController\gpkfPathOpt\library\gpkfPathOptWithRGPAirborne.mat
del .\compositions\hiLvlController\gpkfPathOpt\library\gpkfPathOpt.mat
del .\compositions\hiLvlController\gpkfPathOpt\library\omniscientAltitudeOpt.mat
del .\compositions\hiLvlController\ilcPathOpt\library\basicILC\basicILCThrTen.mat
del .\compositions\hiLvlController\ilcPathOpt\library\basicILC\basicILC.mat
del .\compositions\hiLvlController\ilcPathOpt\library\fig8ILC15mPs\fig8ILC15mPs.mat
del .\compositions\hiLvlController\ilcPathOpt\library\fig8ILC1mPs\fig8ILC1mPs.mat
del .\compositions\hiLvlController\ilcPathOpt\library\fig8ILC2mPs\fig8ILC2mPs.mat
del .\compositions\hiLvlController\ilcPathOpt\library\seILC\seILC.mat
del .\compositions\hiLvlController\varGeom\varGeom.mat
del .\compositions\hiLvlController\variableAltitudeBasisParams\library\varAltitudeBooth\varAltitudeBooth.mat
del .\compositions\hiLvlController\variableRadiusBasisParams\library\varRadiusBooth\varRadiusBooth.mat
del .\compositions\plants\components\groundStations\groundStation000\ayazThreeTetGndStn\ayazThreeTetGndStn.mat
del .\compositions\plants\components\groundStations\groundStation000\oneThrGndStn000\oneThrGndStn000.mat
del .\compositions\plants\components\groundStations\groundStation000\pathFollowingGndStn\pathFollowingGndStn.mat
del .\compositions\plants\components\groundStations\groundStation000\threeThrGndStn000\threeThrGndStn000.mat
del .\compositions\plants\components\groundStations\groundStation001\library\library\oneThrThreeAnchGndStn001\oneThrThreeAnchGndStn001.mat
del .\compositions\plants\components\groundStations\groundStation001\library\oneThrThreeAnchGndStn001\oneThrThreeAnchGndStn001.mat
del .\compositions\plants\components\groundStations\groundStation002\library\resizedKiteGndStn\resizedKiteGndStn.mat
del .\compositions\plants\components\groundStations\groundStationPrescribed\library\prescribedGndStn\prescribedGndStn.mat
del .\compositions\plants\components\groundStations\groundStationPrescribed001\groundStationPrescribed001\library\prescribedGndStn001\prescribedGndStn001.mat
del .\compositions\plants\components\groundStations\groundStationPrescribed001\library\prescribedGndStn001\prescribedGndStn001.mat
del .\compositions\plants\components\groundStations\gsWave\library\gsWave.mat
del .\compositions\plants\components\groundStations\raftGroundStation\library\raftGroundStation\raftGroundStation.mat
del .\compositions\plants\components\tethers\tether000\library\ayazAirborneThr\ayazAirborneThr.mat
del .\compositions\plants\components\tethers\tether000\library\ayazFullScaleOneThrTether\ayazFullScaleOneThrTether.mat
del .\compositions\plants\components\tethers\tether000\library\ayazThreeTetTethers\ayazThreeTetTethers.mat
del .\compositions\plants\components\tethers\tether000\library\fiveNodeSingleTether\fiveNodeSingleTether.mat
del .\compositions\plants\components\tethers\tether000\library\ObsTether\ObsTether.mat
del .\compositions\plants\components\tethers\tether000\library\pathFollowingTether\pathFollowingTether.mat
del .\compositions\plants\components\tethers\tether001\library\shortTether\shortTether.mat
del .\compositions\plants\components\tethers\tether001\library\shortTetherCompare\shortTetherCompare.mat
del .\compositions\plants\components\tethers\tetherFaired\pathFollowingTetherFaired.mat
del .\compositions\plants\components\vehicle\vehicle000\library\ayazThreeTetVhcl\ayazThreeTetVhcl.mat
del .\compositions\plants\components\vehicle\vehicle000\library\pathFollowingVhcl\pathFollowingVhcl.mat
del .\compositions\plants\components\vehicle\vehicleLE\library\ayazAirborneVhcl\ayazAirborneVhcl.mat
del .\compositions\plants\components\vehicle\vehicleLE\library\ayazAirborneVhcl\realisticAirborneVhcl.mat
del .\compositions\plants\components\vehicle\vehicleLE\library\ayazFullScaleOneThrVhcl\ayazFullScaleOneThrVhcl.mat
del .\compositions\plants\components\vehicle\vehicleLE\library\ayazOptVhcl\ayazOptVhcl.mat
del .\compositions\plants\components\vehicle\vehicleLE\library\ayazThreeTetVhclForComp\ayazThreeTetVhclForComp.mat
del .\compositions\plants\components\vehicle\vehicleLE\library\fullScale1thr\fullScale1thr.mat
del .\compositions\plants\components\vehicle\vehicleLE\library\fullScale1thrMod\fullScale1thrMod.mat
del .\compositions\plants\components\vehicle\vehicleLE\library\KartikExperiment\sensitivityAnalysis.mat
del .\compositions\plants\components\vehicle\vehicleLE\library\pathFollowingVhclForComp\pathFollowingVhclForComp.mat
del .\compositions\plants\components\vehicle\vehicleTurbine\library\XFoil\poolScaleKiteAbneyDragScreens.mat
del .\compositions\plants\components\vehicle\vehicleTurbine\library\XFoil\poolScaleKiteAbneyRefined.mat
del .\compositions\plants\components\vehicle\vehicleTurbine\library\XFoil\poolScaleKiteAbney.mat
del .\compositions\plants\components\vehicle\vehicleTurbine\library\XFoil\poolScaleKite.mat
del .\compositions\plants\components\winches\winch000\library\anchWnch\anchWnch.mat
del .\compositions\plants\components\winches\winch000\library\ayazFullScaleOneThrWinch\ayazFullScaleOneThrWinch.mat
del .\compositions\plants\components\winches\winch000\library\ayazThreeTetWnch\ayazThreeTetWnch.mat
del .\compositions\plants\components\winches\winch000\library\oneDOFWnch\oneDOFWnch.mat
del .\compositions\plants\components\winches\winch000\library\oneWnch\oneWnch.mat
del .\compositions\plants\components\winches\winch000\library\threeWnch\threeWnch.mat
del .\compositions\plants\components\winches\winch001\library\oneDOFWnchPTO\oneDOFWnchPTO.mat
del .\compositions\sensorProcessing\idealSensorProcessing\library\idealSensorProcessing\idealSensorProcessing.mat
del .\compositions\sensorProcessing\realisticSensorProcessing\library\realisticSensorProcessing\realisticSensorProcessing.mat
del .\compositions\sensors\deadRecPos\deadRecPos.mat
del .\compositions\sensors\idealSensors\library\idealSensors\idealSensors.mat
del .\compositions\sensors\lasPosEst\library\lasPosEst\lasPosEst.mat
del .\compositions\sensors\lineAngleSensor\library\lineAngleSensorBoat.mat
del .\compositions\sensors\lineAngleSensor\library\lineAngleSensor.mat
del .\compositions\sensors\lineAngleSensorObserver\library\lineAngleSensorObserver.mat
del .\compositions\sensors\realisticSensors\library\realisticSensors\realisticSensors.mat
del .\units\applicationSpecific\lowFreqFlowData\library\CNAPsMitchell\CNAPsMitchell.mat

del .\compositions\environment\flowCalculation\constT_XYZvarZ_Ramp\library\constT_XYZvarZ_Ramp.txt
del .\compositions\environment\flowCalculation\constXYZT\library\constXYZT.txt
del .\compositions\environment\flowCalculation\constXYZT\library\ayazAirborneFlow\ayazAirborneFlow.txt
del .\compositions\environment\flowCalculation\constXYZ_varT_SineWave\library\constXYZ_varT_SineWave.txt
del .\compositions\environment\flowCalculation\constYZTvarX\library\constYZTvarX.txt
del .\compositions\environment\flowCalculation\lowFreqWithFAUTurb\library\CNAPsNoTurbJosh\CNAPsNoTurbJosh.txt
del .\compositions\environment\flowCalculation\lowFreqWithFAUTurb\library\CNAPsTurbJames\CNAPsTurbJames.txt
del .\compositions\environment\flowCalculation\lowFreqWithFAUTurb\library\CNAPsTurbMitchell\CNAPsTurbMitchell.txt
del .\compositions\environment\flowCalculation\lowFreqWithFAUTurb\library\DARPATurbJames\DARPATurbJames.txt
del .\compositions\environment\flowCalculation\lowFreqWithFauTurbAndWaves\library\CNAPsTurbJames.txt
del .\compositions\environment\flowCalculation\planarWaveModel\library\hurricaneSandyWave.txt
del .\compositions\environment\flowCalculation\steppedLateralFlow\library\steppedLateralFlow.txt
del .\compositions\environment\flowCalculation\syntheticFlow\library\ayazAirborneSynFlow.txt
del .\compositions\environment\flowCalculation\syntheticFlow\library\ayazSynFlow.txt
del .\compositions\flightController\fullCycleController\library\fullCycleCtrl\fullCycleCtrl.txt
del .\compositions\flightController\guidanceLawPathFollowing\library\guidanceLawPathFollowingAir\guidanceLawPathFollowingAir.txt
del .\compositions\flightController\guidanceLawPathFollowing\library\guidanceLawPathFollowingWater\guidanceLawPathFollowingWater.txt
del .\compositions\flightController\pathFollowingController\library\pathFollowingCtrlAddedMass\pathFollowingCtrlAddedMass.txt
del .\compositions\flightController\pathFollowingController\library\pathFollowingCtrlForILC\pathFollowingCtrlForILC.txt
del .\compositions\flightController\pathFollowingController\library\pathFollowingCtrlForILC\library\ayazPathFollowingAirborne\ayazPathFollowingAirborne.txt
del .\compositions\flightController\pathFollowingCtrlAoATurb\library\pathFollowCtrlExp.txt
del .\compositions\flightController\pathFollowingCtrlAoATurb\library\pathFollowWithAoACtrlDOE.txt
del .\compositions\flightController\pathFollowingCtrlAoATurb\library\pathFollowingCtrlForManta\pathFollowingCtrlForILCAoA.txt
del .\compositions\flightController\poolTestControllers\library\newSpoolCtrlExp\newSpoolCtrlExp.txt
del .\compositions\flightController\poolTestControllers\library\periodicCtrlExp\periodicCtrlExp.txt
del .\compositions\flightController\shortLeashController\library\slCtrl\exp_slCtrl.txt
del .\compositions\flightController\shortLeashController\library\slCtrl\slCtrl.txt
del .\compositions\flightController\steadyLevelFlightController\library\baselineSteadyLevelFlight\baselineSteadyLevelFlight.txt
del .\compositions\flightController\takeoffToLanding\library\firstBuildTakeoff\firstBuildTakeoff1.txt
del .\compositions\flightController\takeoffToLanding\library\firstBuildTakeoff\firstBuildTakeoff.txt
del .\compositions\flightController\takeoffToLanding\library\jamesMultiCycleExp\jamesMultiCycleExp.txt
del .\compositions\flightController\takeoffToLanding\library\joshMultiCycleExp\joshMultiCycleExp.txt
del .\compositions\flightController\takeoffToLanding\library\newSpoolCtrl\newSpoolCtrl.txt
del .\compositions\flightController\threeTetherThreeSurfaceCtrl\library\ayazThreeTetCtrl\ayazThreeTetCtrl.txt
del .\compositions\gndStnController\anchorTetherCtrl\library\srgSwyHvCtrl\srgSwyHvCtrl.txt
del .\compositions\gndStnController\gliderCtrl\library\motionlessGliderCtrl\motionlessGliderCtrl.txt
del .\compositions\gndStnController\oneDoF\library\oneDoFGSCtrlBasic\oneDoFGSCtrlBasic.txt
del .\compositions\hiLvlController\constantBasisParameters\library\constBoothLem\constBoothLem.txt
del .\compositions\hiLvlController\constantBasisParameters\library\constEllipse\constEllipse.txt
del .\compositions\hiLvlController\gpkfPathOpt\library\gpkfAltitudeOptimization.txt
del .\compositions\hiLvlController\gpkfPathOpt\library\gpkfPathOptAirborne.txt
del .\compositions\hiLvlController\gpkfPathOpt\library\gpkfPathOptWithRGPAirborne.txt
del .\compositions\hiLvlController\gpkfPathOpt\library\gpkfPathOpt.txt
del .\compositions\hiLvlController\gpkfPathOpt\library\omniscientAltitudeOpt.txt
del .\compositions\hiLvlController\ilcPathOpt\library\basicILC\basicILCThrTen.txt
del .\compositions\hiLvlController\ilcPathOpt\library\basicILC\basicILC.txt
del .\compositions\hiLvlController\ilcPathOpt\library\fig8ILC15mPs\fig8ILC15mPs.txt
del .\compositions\hiLvlController\ilcPathOpt\library\fig8ILC1mPs\fig8ILC1mPs.txt
del .\compositions\hiLvlController\ilcPathOpt\library\fig8ILC2mPs\fig8ILC2mPs.txt
del .\compositions\hiLvlController\ilcPathOpt\library\seILC\seILC.txt
del .\compositions\hiLvlController\varGeom\varGeom.txt
del .\compositions\hiLvlController\variableAltitudeBasisParams\library\varAltitudeBooth\varAltitudeBooth.txt
del .\compositions\hiLvlController\variableRadiusBasisParams\library\varRadiusBooth\varRadiusBooth.txt
del .\compositions\plants\components\groundStations\groundStation000\ayazThreeTetGndStn\ayazThreeTetGndStn.txt
del .\compositions\plants\components\groundStations\groundStation000\oneThrGndStn000\oneThrGndStn000.txt
del .\compositions\plants\components\groundStations\groundStation000\pathFollowingGndStn\pathFollowingGndStn.txt
del .\compositions\plants\components\groundStations\groundStation000\threeThrGndStn000\threeThrGndStn000.txt
del .\compositions\plants\components\groundStations\groundStation001\library\library\oneThrThreeAnchGndStn001\oneThrThreeAnchGndStn001.txt
del .\compositions\plants\components\groundStations\groundStation001\library\oneThrThreeAnchGndStn001\oneThrThreeAnchGndStn001.txt
del .\compositions\plants\components\groundStations\groundStation002\library\resizedKiteGndStn\resizedKiteGndStn.txt
del .\compositions\plants\components\groundStations\groundStationPrescribed\library\prescribedGndStn\prescribedGndStn.txt
del .\compositions\plants\components\groundStations\groundStationPrescribed001\groundStationPrescribed001\library\prescribedGndStn001\prescribedGndStn001.txt
del .\compositions\plants\components\groundStations\groundStationPrescribed001\library\prescribedGndStn001\prescribedGndStn001.txt
del .\compositions\plants\components\groundStations\gsWave\library\gsWave.txt
del .\compositions\plants\components\groundStations\raftGroundStation\library\raftGroundStation\raftGroundStation.txt
del .\compositions\plants\components\tethers\tether000\library\ayazAirborneThr\ayazAirborneThr.txt
del .\compositions\plants\components\tethers\tether000\library\ayazFullScaleOneThrTether\ayazFullScaleOneThrTether.txt
del .\compositions\plants\components\tethers\tether000\library\ayazThreeTetTethers\ayazThreeTetTethers.txt
del .\compositions\plants\components\tethers\tether000\library\fiveNodeSingleTether\fiveNodeSingleTether.txt
del .\compositions\plants\components\tethers\tether000\library\ObsTether\ObsTether.txt
del .\compositions\plants\components\tethers\tether000\library\pathFollowingTether\pathFollowingTether.txt
del .\compositions\plants\components\tethers\tether001\library\shortTether\shortTether.txt
del .\compositions\plants\components\tethers\tether001\library\shortTetherCompare\shortTetherCompare.txt
del .\compositions\plants\components\tethers\tetherFaired\pathFollowingTetherFaired.txt
del .\compositions\plants\components\vehicle\vehicle000\library\ayazThreeTetVhcl\ayazThreeTetVhcl.txt
del .\compositions\plants\components\vehicle\vehicle000\library\pathFollowingVhcl\pathFollowingVhcl.txt
del .\compositions\plants\components\vehicle\vehicleLE\library\ayazAirborneVhcl\ayazAirborneVhcl.txt
del .\compositions\plants\components\vehicle\vehicleLE\library\ayazAirborneVhcl\realisticAirborneVhcl.txt
del .\compositions\plants\components\vehicle\vehicleLE\library\ayazFullScaleOneThrVhcl\ayazFullScaleOneThrVhcl.txt
del .\compositions\plants\components\vehicle\vehicleLE\library\ayazOptVhcl\ayazOptVhcl.txt
del .\compositions\plants\components\vehicle\vehicleLE\library\ayazThreeTetVhclForComp\ayazThreeTetVhclForComp.txt
del .\compositions\plants\components\vehicle\vehicleLE\library\fullScale1thr\fullScale1thr.txt
del .\compositions\plants\components\vehicle\vehicleLE\library\fullScale1thrMod\fullScale1thrMod.txt
del .\compositions\plants\components\vehicle\vehicleLE\library\KartikExperiment\sensitivityAnalysis.txt
del .\compositions\plants\components\vehicle\vehicleLE\library\pathFollowingVhclForComp\pathFollowingVhclForComp.txt
del .\compositions\plants\components\vehicle\vehicleTurbine\library\XFoil\poolScaleKiteAbneyDragScreens.txt
del .\compositions\plants\components\vehicle\vehicleTurbine\library\XFoil\poolScaleKiteAbneyRefined.txt
del .\compositions\plants\components\vehicle\vehicleTurbine\library\XFoil\poolScaleKiteAbney.txt
del .\compositions\plants\components\vehicle\vehicleTurbine\library\XFoil\poolScaleKite.txt
del .\compositions\plants\components\winches\winch000\library\anchWnch\anchWnch.txt
del .\compositions\plants\components\winches\winch000\library\ayazFullScaleOneThrWinch\ayazFullScaleOneThrWinch.txt
del .\compositions\plants\components\winches\winch000\library\ayazThreeTetWnch\ayazThreeTetWnch.txt
del .\compositions\plants\components\winches\winch000\library\oneDOFWnch\oneDOFWnch.txt
del .\compositions\plants\components\winches\winch000\library\oneWnch\oneWnch.txt
del .\compositions\plants\components\winches\winch000\library\threeWnch\threeWnch.txt
del .\compositions\plants\components\winches\winch001\library\oneDOFWnchPTO\oneDOFWnchPTO.txt
del .\compositions\sensorProcessing\idealSensorProcessing\library\idealSensorProcessing\idealSensorProcessing.txt
del .\compositions\sensorProcessing\realisticSensorProcessing\library\realisticSensorProcessing\realisticSensorProcessing.txt
del .\compositions\sensors\deadRecPos\deadRecPos.txt
del .\compositions\sensors\idealSensors\library\idealSensors\idealSensors.txt
del .\compositions\sensors\lasPosEst\library\lasPosEst\lasPosEst.txt
del .\compositions\sensors\lineAngleSensor\library\lineAngleSensorBoat.txt
del .\compositions\sensors\lineAngleSensor\library\lineAngleSensor.txt
del .\compositions\sensors\lineAngleSensorObserver\library\lineAngleSensorObserver.txt
del .\compositions\sensors\realisticSensors\library\realisticSensors\realisticSensors.txt
del .\units\applicationSpecific\lowFreqFlowData\library\CNAPsMitchell\CNAPsMitchell.txt
pause
