tsc = signalcontainer(logsout);

vhcl.animateSim(tsc,1,...
    'PathFunc',fltCtrl.fcnName.Value,...
    'PlotTracer',true,...
    'FontSize',24,...
    'PowerBar',false,...
    'PlotAxes',false,...
    'TracerDuration',10,...
    'GroundStation',gndStn,...
    'SaveGif',false)