vhcl.animateSim(tsc,1,...
    'PathFunc',fltCtrl.fcnName.Value,...
    'PathPosition',false,...
    'NavigationVecs',false,...
    'Pause',false,...
    'SaveGif',true,...
    'GifTimeStep',0.05,...
    'ZoomIn',false,...
    'FontSize',20,...
    'PowerBar',false,...
    'ColorTracer',true,...
    'View',[60,20]);

