function val = calcTargetDistance(aBooth,bBooth,meanElevation,radius,s0,L1,ds)

eqPathLength = @(aBooth,bBooth,meanElevation,pathParam,thrLength)sqrt((thrLength.*sin(meanElevation-(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).*sin(pathParam))./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0)).*sin((aBooth.*sin(pathParam))./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0)).*((aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2)./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0)-(aBooth.^2.*1.0./bBooth.^2.*sin(pathParam).^2)./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0)+aBooth.^4.*1.0./bBooth.^4.*cos(pathParam).^2.*sin(pathParam).^2.*1.0./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0).^2.*2.0)+thrLength.*cos(meanElevation-(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).*sin(pathParam))./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0)).*cos((aBooth.*sin(pathParam))./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0)).*((aBooth.*cos(pathParam))./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0)+aBooth.^3.*1.0./bBooth.^2.*cos(pathParam).*sin(pathParam).^2.*1.0./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0).^2.*2.0)).^2+(thrLength.*sin(meanElevation-(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).*sin(pathParam))./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0)).*cos((aBooth.*sin(pathParam))./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0)).*((aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2)./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0)-(aBooth.^2.*1.0./bBooth.^2.*sin(pathParam).^2)./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0)+aBooth.^4.*1.0./bBooth.^4.*cos(pathParam).^2.*sin(pathParam).^2.*1.0./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0).^2.*2.0)-thrLength.*cos(meanElevation-(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).*sin(pathParam))./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0)).*sin((aBooth.*sin(pathParam))./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0)).*((aBooth.*cos(pathParam))./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0)+aBooth.^3.*1.0./bBooth.^2.*cos(pathParam).*sin(pathParam).^2.*1.0./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0).^2.*2.0)).^2+thrLength.^2.*cos(meanElevation-(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).*sin(pathParam))./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0)).^2.*((aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2)./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0)-(aBooth.^2.*1.0./bBooth.^2.*sin(pathParam).^2)./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0)+aBooth.^4.*1.0./bBooth.^4.*cos(pathParam).^2.*sin(pathParam).^2.*1.0./(aBooth.^2.*1.0./bBooth.^2.*cos(pathParam).^2+1.0).^2.*2.0).^2);

val = (L1 - ...
    integral(@(s) eqPathLength(aBooth,bBooth,meanElevation,s,radius),s0,...
    s0+ds))^2;


end