
% superimpose plots from simulation and experiment
% datFileName = 'data_24_Jan_2020_15_50_38.mat';
% fullFileName = strcat(cd,'\Jan24DataFiles\',datFileName);

% tscExp = processExpData(fullFileName,...
%     'Ro_c_in_meters',[22;0;-3.9]./100,...
%     'yawOffset',1*2.5);

% define time to observe
timeExp = tscExp.roll_rad.Time;
tStart = 100; %change to 0 if needed.
tEnd = numel(timeExp);
% tEnd = 15001;
tPlot = tStart:tEnd;

% resample simulation results
resampleDataRate = 0.01;
signals = fieldnames(tscSim);
timeAnim = 0:resampleDataRate:tscSim.(signals{1}).Time(end);
timeSim2 = timeAnim;

tscSim2.positionVec = resample(tscSim.positionVec,timeAnim);
tscSim2.velocityVec = resample(tscSim.velocityVec,timeAnim);
tscSim2.eulerAngles = resample(tscSim.eulerAngles,timeAnim);
tscSim2.angularVel = resample(tscSim.angularVel,timeAnim);
tscSim2.rollSetpoint = resample(tscSim.rollSetpoint,timeAnim);
tscSim2.pitchSetpoint = resample(tscSim.pitchSetpoint,timeAnim);
tscSim2.thrReleaseSpeeds = resample(tscSim.thrReleaseSpeeds,timeAnim);

sol_Rcm_o = repmat(gndStn.posVec.Value(:),1,numel(timeSim2))...
    + squeeze(tscSim2.positionVec.Data).*(1/Lscale);
sol_Vcmo = squeeze(tscSim2.velocityVec.Data).*(1/Lscale^0.5);
sol_euler = squeeze(tscSim2.eulerAngles.Data);
sol_OwB = squeeze(tscSim2.angularVel.Data).*(Lscale^0.5);

[objF2,rmseVals,othrVals] = calObjF(tscSim2,tscExp,dataRange);

% % % % shift the time axis
timeSim2 = timeSim2 - 50;
timeExp = timeExp - 50;

% % % euler angles %%%%%%%%%%%%%%%%%%%%%%%%%
fn = fn+1;
figure(fn)
set(gcf,'Position',locs(fn,:))
% % % % simulation
vectorPlotter(timeSim2,sol_euler*180/pi,...
    'legends',{'$\phi_{sim}$','$\theta_{sim}$','$\psi_{sim}$'},...
    'ylabels',{'Roll','Pitch','Yaw'},...
    'yUnits','(deg)',...
    'figureTitle','Euler angles');
% % % % experiment
vectorPlotter(timeExp(tPlot),(180/pi)*[tscExp.roll_rad.Data(tPlot)';...
    tscExp.pitch_rad.Data(tPlot)';...
    tscExp.yaw_rad.Data(tPlot)'],...
    'lineSpec','--',...
    'legends',{'$\phi_{exp}$','$\theta_{exp}$','$\psi_{exp}$'},...
    'ylabels',{'Roll','Pitch','Yaw'},...
    'yUnits','(deg)',...
    'figureTitle','Euler angles');
% % % % setpoints
subplot(3,1,1)
plot(timeSim2,squeeze(tscSim2.rollSetpoint.Data),'k--',...
    'DisplayName','$\phi_{sp}$');
subplot(3,1,2)
plot(timeSim2,squeeze(tscSim2.pitchSetpoint.Data),'k--',...
    'DisplayName','$\theta_{sp}$');

subplot(3,1,1)
plot(timeExp(tPlot),(180/pi)*tscExp.RollSetpoint.Data(tPlot),'k--','linewidth',0.75)
legend('$\phi$','SP')


% % % % CM positions  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fn = fn+1;
figure(fn);
set(gcf,'Position',locs(fn,:))
% % % % simulation
vectorPlotter(timeSim2,sol_Rcm_o,...
    'legends',{'$x_{sim}$','$y_{sim}$','$z_{sim}$'},...
    'ylabels',{'$x_{cm}$','$y_{cm}$','$z_{cm}$'},...
    'yUnits','(m)',...
    'figureTitle','CM position');
% % % % experiment
vectorPlotter(timeExp(tPlot),squeeze(tscExp.CoMPosVec_cm.Data(:,tPlot)),...
    'lineSpec','--',...
    'legends',{'$x_{exp}$','$y_{exp}$','$z_{exp}$'},...
    'ylabels',{'$x_{cm}$','$y_{cm}$','$z_{cm}$'},...
    'yUnits','(m)',...
    'figureTitle','CM position');

subplot(3,1,1)
title('CM position');

% % % % controller command
fn = fn+1;
figure(fn)
set(gcf,'Position',locs(fn,:))
% % % % simulation
vectorPlotter(timeSim2,tscSim2.thrReleaseSpeeds.Data',...
    'legends',{'$u_{port,sim}$','$u_{aft,sim}$','$u_{stbd,sim}$'},...
    'ylabels',{'$u_{port}$','$u_{aft}$','$u_{stbd}$'},...
    'yUnits','(m/s)',...
    'figureTitle','Tether release speeds');
% % % % experiment
vectorPlotter(timeExp(tPlot),wnch.winch1.maxSpeed.Value.*squeeze(tscExp.mtrCmds.Data(:,tPlot)),...
    'lineSpec','--',...
    'legends',{'$u_{port,exp}$','$u_{aft,exp}$','$u_{stbd,exp}$'},...
    'ylabels',{'$u_{port}$','$u_{aft}$','$u_{stbd}$'},...
    'yUnits','(m/s)',...
    'figureTitle','Tether release speeds');

% % % % cm velocity
fn = fn+1;
figure(fn)
set(gcf,'Position',locs(fn,:))
vectorPlotter(timeSim2,sol_Vcmo,...
    'legends',{'$V_{x,sim}$','$V_{y,sim}$','$V_{z,sim}$'},...
    'ylabels',{'$V_x$','$V_y$','$V_z$'},...
    'yUnits','(m/s)',...
    'figureTitle','CM velocity');

vectorPlotter(timeExp(tPlot(1:end-2)),tscExp.CoMVelVec_cm.Data(:,tPlot(1:end-2)),...
    'lineSpec','--',...
    'legends',{'$V_{x,sim}$','$V_{y,sim}$','$V_{z,sim}$'},...
    'ylabels',{'$V_x$','$V_y$','$V_z$'},...
    'yUnits','(m/s)',...
    'figureTitle','CM velocity');
subplot(3,1,1)
title('CM velocity')

%%%%%%
set(findobj('Type','axes'),'XLim',[0 60]);
set(findobj('Type','legend'),'Visible','off');
% set(findall(gcf,'-property','FontSize'),'FontSize',13)
