function val = scaleParam(p,factor)
val = p.Value;
if ~p.IgnoreScaling && ~isempty(p.Value) && ~isempty(p.Unit)
    scaleUnitList = {'m','s','kg','rad','deg','N','Pa'}; % units that impact how to scale things
    scaleFactorList  = {...
        'factor',...
        'sqrt(factor)',...
        '(factor^3)',...
        '1',...
        '1',...
        'factor^3',...
        'factor'};
    units = p.Unit;
    for ii = 1:length(scaleUnitList)
        units = strrep(units,scaleUnitList{ii},scaleFactorList{ii});
    end
    val = p.Value*eval(units);
end
end