% Script to animate simulation
% sim('threeTetherVerification_th')
tsc = parseLogsout;
% close all
resampleDataRate = 0.1;
filename = 'testAnimated.gif';
signals = fieldnames(tsc);

tenVecLength = 50;

newTimeVec = 0:resampleDataRate:tsc.(signals{1}).Time(end);
for ii = 1:length(signals)
    tscResample.(signals{ii}) = resample(tsc.(signals{ii}),newTimeVec);
end
h.fig = figure('Position',[   0    0.0370    1.0000    0.8917],...
    'Color','w');
h.ax = axes('NextPlot','add');

h.origin = scatter3(0,0,0,'Marker','o','CData',[0 1 0],...
    'MarkerFaceColor',[0 1 0]);

h.position = scatter3(tscResample.posVec.data(1,:,1),...
    tscResample.posVec.data(2,:,1),...
    tscResample.posVec.data(3,:,1),'Marker','o','CData',[1 0 0],...\
    'MarkerFaceColor','flat');

h.thr1AtchGrndPt = plot3(...
    [0 tscResample.thr1AtchGrndPt.Data(1,1)],...
    [0 tscResample.thr1AtchGrndPt.Data(1,2)],...
    [0 tscResample.thr1AtchGrndPt.Data(1,3)],...
    'Color','k','LineWidth',2,'LineStyle','-');
h.thr2AtchGrndPt = plot3(...
    [0 tscResample.thr2AtchGrndPt.Data(1,1)],...
    [0 tscResample.thr2AtchGrndPt.Data(1,2)],...
    [0 tscResample.thr2AtchGrndPt.Data(1,3)],...
    'Color','k','LineWidth',2,'LineStyle','-');
h.thr3AtchGrndPt = plot3(...
    [0 tscResample.thr3AtchGrndPt.Data(1,1)],...
    [0 tscResample.thr3AtchGrndPt.Data(1,2)],...
    [0 tscResample.thr3AtchGrndPt.Data(1,3)],...
    'Color','k','LineWidth',2,'LineStyle','-');


h.thr1AtchAirPt = plot3(...
    [tscResample.posVec.Data(1,:,1) tscResample.thr1AtchAirPt.Data(1,:,1)],...
    [tscResample.posVec.Data(2,:,1) tscResample.thr1AtchAirPt.Data(2,:,1)],...
    [tscResample.posVec.Data(3,:,1) tscResample.thr1AtchAirPt.Data(3,:,1)],...
    'Color','k','LineWidth',2,'LineStyle','-');
h.thr2AtchAirPt = plot3(...
    [tscResample.posVec.Data(1,:,1) tscResample.thr2AtchAirPt.Data(1,:,1)],...
    [tscResample.posVec.Data(2,:,1) tscResample.thr2AtchAirPt.Data(2,:,1)],...
    [tscResample.posVec.Data(3,:,1) tscResample.thr2AtchAirPt.Data(3,:,1)],...
    'Color','k','LineWidth',2,'LineStyle','-');
h.thr3AtchAirPt = plot3(...
    [tscResample.posVec.Data(1,:,1) tscResample.thr3AtchAirPt.Data(1,:,1)],...
    [tscResample.posVec.Data(2,:,1) tscResample.thr3AtchAirPt.Data(2,:,1)],...
    [tscResample.posVec.Data(3,:,1) tscResample.thr3AtchAirPt.Data(3,:,1)],...
    'Color','k','LineWidth',2,'LineStyle','-');


h.thr1 = plot3(...
    tscResample.thr1NodePos.Data(1,:,1),...
    tscResample.thr1NodePos.Data(2,:,1),...
    tscResample.thr1NodePos.Data(3,:,1),...
    'Color','b','LineWidth',1,'LineStyle','-','Marker','x');

h.thr2 = plot3(...
    tscResample.thr2NodePos.Data(1,:,1),...
    tscResample.thr2NodePos.Data(2,:,1),...
    tscResample.thr2NodePos.Data(3,:,1),...
    'Color','b','LineWidth',1,'LineStyle','-','Marker','x');

h.thr3 = plot3(...
    tscResample.thr3NodePos.Data(1,:,1),...
    tscResample.thr3NodePos.Data(2,:,1),...
    tscResample.thr3NodePos.Data(3,:,1),...
    'Color','b','LineWidth',1,'LineStyle','-','Marker','x');

ten1AirUnitVec = tscResample.thr1AirTenVec.Data(:,:,1)./norm(tscResample.thr1AirTenVec.Data(:,:,1));
ten2AirUnitVec = tscResample.thr2AirTenVec.Data(:,:,1)./norm(tscResample.thr2AirTenVec.Data(:,:,1));
ten3AirUnitVec = tscResample.thr3AirTenVec.Data(:,:,1)./norm(tscResample.thr3AirTenVec.Data(:,:,1));

h.ten1Air = quiver3(...
    tscResample.thr1AtchAirPt.Data(1,:,1),...
    tscResample.thr1AtchAirPt.Data(2,:,1),...
    tscResample.thr1AtchAirPt.Data(3,:,1),...
    tenVecLength*ten1AirUnitVec(1),...
    tenVecLength*ten1AirUnitVec(2),...
    tenVecLength*ten1AirUnitVec(3),...
    'Color',[1 0 0],'LineStyle','-','LineWidth',1.5);

h.ten2Air = quiver3(...
    tscResample.thr2AtchAirPt.Data(1,:,1),...
    tscResample.thr2AtchAirPt.Data(2,:,1),...
    tscResample.thr2AtchAirPt.Data(3,:,1),...
    tenVecLength*ten2AirUnitVec(1),...
    tenVecLength*ten2AirUnitVec(2),...
    tenVecLength*ten2AirUnitVec(3),...
    'Color',[1 0 0],'LineStyle','-','LineWidth',1.5);

h.ten3Air = quiver3(...
    tscResample.thr3AtchAirPt.Data(1,:,1),...
    tscResample.thr3AtchAirPt.Data(2,:,1),...
    tscResample.thr3AtchAirPt.Data(3,:,1),...
    tenVecLength*ten3AirUnitVec(1),...
    tenVecLength*ten3AirUnitVec(2),...
    tenVecLength*ten3AirUnitVec(3),...
    'Color',[1 0 0],'LineStyle','-','LineWidth',1.5);


ten1GrndUnitVec = tscResample.thr1GrndTenVec.Data(:,:,1)./norm(tscResample.thr1GrndTenVec.Data(:,:,1));
ten2GrndUnitVec = tscResample.thr2GrndTenVec.Data(:,:,1)./norm(tscResample.thr2GrndTenVec.Data(:,:,1));
ten3GrndUnitVec = tscResample.thr3GrndTenVec.Data(:,:,1)./norm(tscResample.thr3GrndTenVec.Data(:,:,1));

h.ten1Grnd = quiver3(...
    tscResample.thr1AtchGrndPt.Data(1,1),...
    tscResample.thr1AtchGrndPt.Data(1,2),...
    tscResample.thr1AtchGrndPt.Data(1,3),...
    tenVecLength*ten1GrndUnitVec(1),...
    tenVecLength*ten1GrndUnitVec(2),...
    tenVecLength*ten1GrndUnitVec(3),...
    'Color',[1 0 0],'LineStyle','-','LineWidth',1.5);

h.ten2Grnd = quiver3(...
    tscResample.thr2AtchGrndPt.Data(1,1),...
    tscResample.thr2AtchGrndPt.Data(1,2),...
    tscResample.thr2AtchGrndPt.Data(1,3),...
    tenVecLength*ten2GrndUnitVec(1),...
    tenVecLength*ten2GrndUnitVec(2),...
    tenVecLength*ten2GrndUnitVec(3),...
    'Color',[1 0 0],'LineStyle','-','LineWidth',1.5);

h.ten3Grnd = quiver3(...
    tscResample.thr3AtchGrndPt.Data(1,1),...
    tscResample.thr3AtchGrndPt.Data(1,2),...
    tscResample.thr3AtchGrndPt.Data(1,3),...
    tenVecLength*ten3GrndUnitVec(1),...
    tenVecLength*ten3GrndUnitVec(2),...
    tenVecLength*ten3GrndUnitVec(3),...
    'Color',[1 0 0],'LineStyle','-','LineWidth',1.5);

grid on
axis square
axis equal
view([25.2373,17.6782])
% xlim([-50 150])
% ylim([-50 50])
% zlim([0 250])

h.title = title(sprintf('Time = %.1f',0));
set(gca,'FontSize',20)

frame = getframe(h.fig);
im = frame2im(frame);
[imind,cm] = rgb2ind(im,256);
imwrite(imind,cm,filename,'gif', 'Loopcount',inf,'DelayTime',1/30);
for ii = 2:numel(tscResample.(signals{1}).Time)
    
    h.title.String = sprintf('Time = %.1f',tscResample.(signals{1}).Time(ii));
    h.position.XData = tscResample.posVec.data(1,:,ii);
    h.position.YData = tscResample.posVec.data(2,:,ii);
    h.position.ZData = tscResample.posVec.data(3,:,ii);
    
    h.thr1AtchGrndPt.XData = [0 tscResample.thr1AtchGrndPt.Data(ii,1)];
    h.thr1AtchGrndPt.YData = [0 tscResample.thr1AtchGrndPt.Data(ii,2)];
    h.thr1AtchGrndPt.ZData = [0 tscResample.thr1AtchGrndPt.Data(ii,3)];
    
    h.thr2AtchGrndPt.XData = [0 tscResample.thr2AtchGrndPt.Data(ii,1)];
    h.thr2AtchGrndPt.YData = [0 tscResample.thr2AtchGrndPt.Data(ii,2)];
    h.thr2AtchGrndPt.ZData = [0 tscResample.thr2AtchGrndPt.Data(ii,3)];
    
    h.thr3AtchGrndPt.XData = [0 tscResample.thr3AtchGrndPt.Data(ii,1)];
    h.thr3AtchGrndPt.YData = [0 tscResample.thr3AtchGrndPt.Data(ii,2)];
    h.thr3AtchGrndPt.ZData = [0 tscResample.thr3AtchGrndPt.Data(ii,3)];
    
    h.thr1AtchAirPt.XData = [tscResample.posVec.Data(1,:,ii) tscResample.thr1AtchAirPt.Data(1,:,ii)];
    h.thr1AtchAirPt.YData = [tscResample.posVec.Data(2,:,ii) tscResample.thr1AtchAirPt.Data(2,:,ii)];
    h.thr1AtchAirPt.ZData = [tscResample.posVec.Data(3,:,ii) tscResample.thr1AtchAirPt.Data(3,:,ii)];
    
    h.thr2AtchAirPt.XData = [tscResample.posVec.Data(1,:,ii) tscResample.thr2AtchAirPt.Data(1,:,ii)];
    h.thr2AtchAirPt.YData = [tscResample.posVec.Data(2,:,ii) tscResample.thr2AtchAirPt.Data(2,:,ii)];
    h.thr2AtchAirPt.ZData = [tscResample.posVec.Data(3,:,ii) tscResample.thr2AtchAirPt.Data(3,:,ii)];
    
    h.thr3AtchAirPt.XData = [tscResample.posVec.Data(1,:,ii) tscResample.thr3AtchAirPt.Data(1,:,ii)];
    h.thr3AtchAirPt.YData = [tscResample.posVec.Data(2,:,ii) tscResample.thr3AtchAirPt.Data(2,:,ii)];
    h.thr3AtchAirPt.ZData = [tscResample.posVec.Data(3,:,ii) tscResample.thr3AtchAirPt.Data(3,:,ii)];
    
    h.thr1.XData = tscResample.thr1NodePos.Data(1,:,ii);
    h.thr1.YData = tscResample.thr1NodePos.Data(2,:,ii);
    h.thr1.ZData = tscResample.thr1NodePos.Data(3,:,ii);
    
    h.thr2.XData = tscResample.thr2NodePos.Data(1,:,ii);
    h.thr2.YData = tscResample.thr2NodePos.Data(2,:,ii);
    h.thr2.ZData = tscResample.thr2NodePos.Data(3,:,ii);
    
    h.thr3.XData = tscResample.thr3NodePos.Data(1,:,ii);
    h.thr3.YData = tscResample.thr3NodePos.Data(2,:,ii);
    h.thr3.ZData = tscResample.thr3NodePos.Data(3,:,ii);
    
    % Airborne tension vectors
    ten1AirUnitVec = tscResample.thr1AirTenVec.Data(:,:,ii)./norm(tscResample.thr1AirTenVec.Data(:,:,ii));
    ten2AirUnitVec = tscResample.thr2AirTenVec.Data(:,:,ii)./norm(tscResample.thr2AirTenVec.Data(:,:,ii));
    ten3AirUnitVec = tscResample.thr3AirTenVec.Data(:,:,ii)./norm(tscResample.thr3AirTenVec.Data(:,:,ii));
    
    h.ten1Air.XData = tscResample.thr1AtchAirPt.Data(1,:,ii);
    h.ten1Air.YData = tscResample.thr1AtchAirPt.Data(2,:,ii);
    h.ten1Air.ZData = tscResample.thr1AtchAirPt.Data(3,:,ii);
    h.ten1Air.UData = tenVecLength*ten1AirUnitVec(1);
    h.ten1Air.VData = tenVecLength*ten1AirUnitVec(2);
    h.ten1Air.WData = tenVecLength*ten1AirUnitVec(3);
    
    h.ten2Air.XData = tscResample.thr2AtchAirPt.Data(1,:,ii);
    h.ten2Air.YData = tscResample.thr2AtchAirPt.Data(2,:,ii);
    h.ten2Air.ZData = tscResample.thr2AtchAirPt.Data(3,:,ii);
    h.ten2Air.UData = tenVecLength*ten2AirUnitVec(1);
    h.ten2Air.VData = tenVecLength*ten2AirUnitVec(2);
    h.ten2Air.WData = tenVecLength*ten2AirUnitVec(3);
    
    h.ten3Air.XData = tscResample.thr3AtchAirPt.Data(1,:,ii);
    h.ten3Air.YData = tscResample.thr3AtchAirPt.Data(2,:,ii);
    h.ten3Air.ZData = tscResample.thr3AtchAirPt.Data(3,:,ii);
    h.ten3Air.UData = tenVecLength*ten3AirUnitVec(1);
    h.ten3Air.VData = tenVecLength*ten3AirUnitVec(2);
    h.ten3Air.WData = tenVecLength*ten3AirUnitVec(3);
    
    % Ground station tension vectors
    ten1GrndUnitVec = tscResample.thr1GrndTenVec.Data(:,:,ii)./norm(tscResample.thr1GrndTenVec.Data(:,:,ii));
    ten2GrndUnitVec = tscResample.thr2GrndTenVec.Data(:,:,ii)./norm(tscResample.thr2GrndTenVec.Data(:,:,ii));
    ten3GrndUnitVec = tscResample.thr3GrndTenVec.Data(:,:,ii)./norm(tscResample.thr3GrndTenVec.Data(:,:,ii));
    
    h.ten1Grnd.XData = tscResample.thr1AtchGrndPt.Data(ii,1);
    h.ten1Grnd.YData = tscResample.thr1AtchGrndPt.Data(ii,2);
    h.ten1Grnd.ZData = tscResample.thr1AtchGrndPt.Data(ii,3);
    h.ten1Grnd.UData = tenVecLength*ten1GrndUnitVec(1);
    h.ten1Grnd.VData = tenVecLength*ten1GrndUnitVec(2);
    h.ten1Grnd.WData = tenVecLength*ten1GrndUnitVec(3);
    
    h.ten2Grnd.XData = tscResample.thr2AtchGrndPt.Data(ii,1);
    h.ten2Grnd.YData = tscResample.thr2AtchGrndPt.Data(ii,2);
    h.ten2Grnd.ZData = tscResample.thr2AtchGrndPt.Data(ii,3);
    h.ten2Grnd.UData = tenVecLength*ten2GrndUnitVec(1);
    h.ten2Grnd.VData = tenVecLength*ten2GrndUnitVec(2);
    h.ten2Grnd.WData = tenVecLength*ten2GrndUnitVec(3);
    
    h.ten3Grnd.XData = tscResample.thr3AtchGrndPt.Data(ii,1);
    h.ten3Grnd.YData = tscResample.thr3AtchGrndPt.Data(ii,2);
    h.ten3Grnd.ZData = tscResample.thr3AtchGrndPt.Data(ii,3);
    h.ten3Grnd.UData = tenVecLength*ten3GrndUnitVec(1);
    h.ten3Grnd.VData = tenVecLength*ten3GrndUnitVec(2);
    h.ten3Grnd.WData = tenVecLength*ten3GrndUnitVec(3);
    
    drawnow
    
    frame = getframe(h.fig);
    im = frame2im(frame);
    [imind,cm] = rgb2ind(im,256);
    imwrite(imind,cm,filename,'gif','WriteMode','append','DelayTime',1/30);
end