for ii = 1:numel(aeroStruct)
    zVec = cross(aeroStruct(ii).chordUnitVec,aeroStruct(ii).spanUnitVec);
    aeroStruct(ii).RBdy2Surf = [...
        aeroStruct(ii).chordUnitVec(:)';...
        aeroStruct(ii).spanUnitVec(:)';...
        zVec(:)'];
end